### ISSUE TITLE
Best way to create watchers from outside sentinl application

### ISSUE THREAD

**Issue by seshu3564** [sirensolutions/sentinl#181]
If we have to create watchers through our own application. Can someone suggest best way to do it

way1: Call Sentinl create watcher api's from application.

way2: create watcher in watcher index of elasticsearch using elastic search query with raw body of watcher.

if we use way2 will it affect the listing api of sentinl from fetching watchers in UI.

Thanks in advance

**Comment by lmangani** [comment]
Hi @seshu3564 thanks for using SENTINL and participating other issue discussions with advice.

Creating watchers via our API might be tricky unless your application is also a Kibana/Kibi plugin or at least an authenticated client to them - upcoming versions bring authentication and impersonation of users so this becomes quite relevant. Method 2 might end up being the easiest to start with, and since SENTINL refreshes the indices the watcher and its alarms should display in the UI. If this is not the case, please provide an example and we'll help you sort it out.

**Comment by seshu3564** [comment]
Cool what intrigued me is sentinl storing watcher in different docs like `Later` in one doc and `transform` in one doc and `action` in other doc. so should i store all in same doc or multiple docs

**Comment by lmangani** [comment]
Those are not different docs tho, watchers are self-contained objects.

**Comment by seshu3564** [comment]
Thanks for qucik response i will start by creating watchers in es watcher index

**Comment by lmangani** [comment]
Closing issue but curious if you ever achieved this - could be interesting to extend our Wiki. Thanks!
