### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by lmangani** [sirensolutions/sentinl#187]
SENTINL badly needs a refreshed library of examples to get new users started. This is a call for all existing users to share bits and pieces of their everyday recipes so we can collect them on the Wiki in an ordered fashion?

Thanks in advance to anyone willing to contribute!

**Comment by jmroth** [comment]
How would I edit the wiki?

**Comment by lmangani** [comment]
You cannot at this time indeed unless team member, but feel free to post examples or pointers in this thread and they'll be discussed and included - much appreciated!

**Comment by jmroth** [comment]
For example: Compare condition (https://github.com/sirensolutions/sentinl/wiki/SENTINL-Watcher-Anatomy#compare-condition)
One should make the distinction between the condition when put into "raw" format and the actual condition when input via the "input, condition, translation, action" workflow.
In the first case (raw input) it would be one example of a list only:
```
...
condition: {
  "compare" : {
    "payload.hits.total" : { 
      "gte" : 5 
    }
  }
},
...
```

In the second case, you would need to use:
```
{
condition: {
  "compare" : {
    "payload.hits.total" : { 
      "gte" : 5 
    }
  }
}
}
```
(Otherwise it will complain that it is not valid JSON). (There is a closing curly brace missing in the currently available example anyway.)

**Comment by jmroth** [comment]
Furthermore, concerning the compare condition: You talk about "watch payload". 
After digging into it, I guess that means you will not be able to use it like range filtering (which works on documents)? This is important for beginners and should be clarified.
One should also explain why and when you would need conditions and not simply formulate a corresponding query in the first place.

**Comment by jmroth** [comment]
Oh yeah and if you want to remove a condition alltogether you need to specify
`{}`
instead of just a blank dialog. But that could be a bug too ;-)

**Comment by lmangani** [comment]
@jmroth about the examples, those are intentionally lacking the commas and do require understanding in order to be copy-pasted. I personally find this an educational plus as proper understanding of the format is anyway required in order to advance and succeed with SENTINL. I'm not sure I understand your comment about "watch payload" and range conditions and what should be clarified.

Thanks for your input!

**Comment by lmangani** [comment]
Closing issue, but let's continue the discussion in this thread
