### ISSUE TITLE
Input chaining is not working as expected.

### ISSUE THREAD

**Issue by narayanan1993** [sirensolutions/sentinl#230]
I am facing an issue when chaining the inputs. To add, I am using AWS elasticsearch service and in-house kibana with  sentinl plugin.

I am trying to do is. 

1.) Run query with last 15mins timestamp and fetch the value as A

2.) Run the same query on 7 days back at the same time and fetch the value as B.

3.) Compare A and B, If A is greater than B, I need to trigger an Alert.

More info: 
My ES index are created daily with index-YYYY.MM.dd format.

https://gist.github.com/narayanan1993/580a31a79723d1b91eb9a8141a4f7def

**Comment by lmangani** [comment]
Hi @narayanan1993 we'll need to see what you actually configured in order to help. Chaining is a delicate matter indeed, based on what you're saying you should save the results of 1) and 2) in a dedicated insert using a webhook and check/compare with 3) watcher but I can't suggest much else in the blind.

**Comment by narayanan1993** [comment]
The example is in the below link:

https://gist.github.com/narayanan1993/580a31a79723d1b91eb9a8141a4f7def

**Comment by lmangani** [comment]
I see. You're trying to use a feature not yet implemented in SENTINL. Check back on the next releases as this is in the roadmap and should see light soon.
