### ISSUE TITLE
Anomaly detection not working

### ISSUE THREAD

**Issue by neelrana** [sirensolutions/sentinl#297]
1. Issue Description

Hi, I am trying to set "whitelist" few usernames from the query results and only output usernames that are not in the whitelist (anomalies).

2. Reproducing the Issue step-by-step
Here is the code for 'conditions' section:

```
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      },
      "anomaly": {
        "field_to_check": "event_data.TargetUserName",
        "normal_values": [
            "WIN11$",
            "WINSVR$"
         ]
      }
    },
```

3. Expected Results vs. Actual Results

The watcher still sends alerts with the above usernames in the output for some reason. Have you got any ideas inoder to ignore the whitelisted usernames?

Also is there a way to use filers used in kibana in Sentinl? Please let me know. Thank you

**Comment by lmangani** [comment]
@neelrana Interesting case. Any chance you could provide the actual response for troubleshooting? I suspect the anomaly detection won't work well with strings yet as It was mostly designed with timeseries anomaly in mind rather than terms, but this could be a good time to extend it. On the other hand, this would be easier to do in an actual Elasticsearch query - which brings us to the last question: you can use any valid query in sentinl, there are no limitations - everything goes directly to/from the ES API via the Kibana client just like it would for a visualization.

**Comment by sergibondarenko** [comment]
@neelrana `anomaly` feature works only with numbers. Array `normal_values` should contain numbers. You can read the documentation [here](http://sentinl.readthedocs.io/en/docs/HOWTO-Anomaly-Detection/).

You can filter using normal Elasticsearch [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-bool-query.html) syntax, for example:
```
POST _search
{
  "query": {
    "bool" : {
      "must_not" : [
        { "term" : { "username" : "admin" } },
        { "term" : { "username" : "superuser" } }
      ],
      "minimum_should_match" : 1,
      "boost" : 1.0
    }
  }
}
```
