### ISSUE TITLE
Report email triggers even Condition fail 

### ISSUE THREAD

**Issue by varun0002** [sirensolutions/sentinl#336]
1. Sentinl and Kibana version 5.4.1

2. Issue description: We have a watcher with 2 actions i.e. email & report. Report action always trigger and sends mail even if "No results for current condition".

3. Reproducing the issue step-by-step: Define watcher with 2 actions i.e. email & Report

4. Expected results vs. actual results: Shouldn't trigger any action if condition is not met.

**Comment by sergibondarenko** [comment]
Hi @varun0002 
You see a message like this, right?
![screenshot from 2018-03-12 10-39-56](https://user-images.githubusercontent.com/5389745/37276388-d73ff1ec-25e1-11e8-98ab-766fef3fbc94.png)
It is not error. It is a warning. That's why the color is yellow.
It means that there is not enough data to satisfy condition `payload.hits.total >= 1111110`. And it is intended behavior.

The watcher is executed if fewer docs requested in the condition `payload.hits.total >= 1`
![screenshot from 2018-03-12 10-43-41](https://user-images.githubusercontent.com/5389745/37276590-70696a24-25e2-11e8-8a35-7fd7a9b04476.png)

**Comment by varun0002** [comment]
@sergibondarenko: Thanks for your response. The issue over here is that whether the condition is true or false, it trigger report action. Ideally, the report action shouldn't get trigger if condition returns false. 

I looked at watcher.js and it appears Sentinl doesn't run condition & transform if action is report. I made fix in my local environment and will raise PR for this.

**Comment by sergibondarenko** [comment]
@varun0002 ahh, it is a report action, when you do a screenshot, right? A PR is welcomed.

**Comment by varun0002** [comment]
@sergibondarenko: Raised PR # https://github.com/sirensolutions/sentinl/pull/342
