### ISSUE TITLE
6.3.0

### ISSUE THREAD

**Issue by BFLB** [sirensolutions/sentinl#467]
1. Kibana Version 6.3.0

2. I have Kibana Version 6.3.0 and would like to install sentinl. The latest version of sentinl I can find is 6.2.4, which does not install. Please let  me know if 6.3.0 support exists and where it can be downloaded.
Sincerly Bernhard

**Comment by lmangani** [comment]
@BFLB 6.3.0 is not yet supported, once it will a release will appear with the rest. As usual Elastic decided to break 100 things in undocumented ways for all of us plugin developers.....

**Comment by sergibondarenko** [comment]
@BFLB could you please try to install it in a dev way? 
```
git clone https://github.com/sirensolutions/sentinl
cd sentinl
vim package.json # change kibana.version to 6.3.0
npm install
gulp dev sync --kibanahomepath=/path/to/kibana/folder
```

**Comment by lmangani** [comment]
@sergibondarenko we already tried this in a different issue, there are functional differences (as usual) so the codebase won't run as-is apparently

**Comment by BFLB** [comment]
Hi,
Thank you for your answers. No problem at all. I will wait until an
official version is available.
Regards


2018-06-20 16:11 GMT+02:00 Lorenzo Mangani <notifications@github.com>:

**Comment by lucasalvarezlacasa** [comment]
Hello guys, are there any news on this issue? My team and I are also waiting for this release?

Any ideas on when this might be?

**Comment by jccq** [comment]
Hi Lucas see my previous mail for the official release . Community
contributions welcome or commercial engagement is possible also

>

**Comment by lucasalvarezlacasa** [comment]
Where's your previous mail @jccq ?

**Comment by jccq** [comment]
Ah for some reason it shoed up in my mail but not in this thread. The  official date for 6.x support of the Siren platform is September 30th. so we'll have it most likely prior to that date.

**Comment by TastyMuffins** [comment]
Just thought I would add. Changing a 6.2.4 package.json and attempting to install, fails with the following problem of os.tmpDir() to os.tmpdir()

Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:22241) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })
    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:31:11)
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:14:95
    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:13:83
    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:42)
    at Array.reduce (<anonymous>)
    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:20)
    at Array.reduce (<anonymous>)
    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:20:18)
    at Array.reduce (<anonymous>)
    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:16:22)
    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)
    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)
    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)
    at <anonymous>

{"type":"log","@timestamp":"2018-08-21T22:56:42Z","tags":["warning","config","deprecation"],"pid":22241,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"error","@timestamp":"2018-08-21T22:56:46Z","tags":["fatal"],"pid":22241,"level":"fatal","error":{"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })","name":"Error","stack":"Error: [plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })\n    at applySpecDefaults (/usr/share/kibana/src/ui/ui_exports/ui_export_types/ui_apps.js:31:11)\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/map_spec.js:14:95\n    at /usr/share/kibana/src/ui/ui_exports/ui_export_types/modify_reduce/alias.js:13:83\n    at specs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:42)\n    at Array.reduce (<anonymous>)\n    at types.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:31:20)\n    at Array.reduce (<anonymous>)\n    at pluginSpecs.reduce (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:20:18)\n    at Array.reduce (<anonymous>)\n    at reduceExportSpecs (/usr/share/kibana/src/plugin_discovery/plugin_exports/reduce_export_specs.js:16:22)\n    at collectUiExports (/usr/share/kibana/src/ui/ui_exports/collect_ui_exports.js:19:50)\n    at KbnServer.uiExportsMixin (/usr/share/kibana/src/ui/ui_exports/ui_exports_mixin.js:11:66)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)\n    at KbnServer.uiMixin (/usr/share/kibana/src/ui/ui_mixin.js:27:19)\n    at KbnServer.mixin (/usr/share/kibana/src/server/kbn_server.js:136:16)\n    at <anonymous>"},"message":"[plugin:sentinl] uiExports.app.injectVars has been removed. Use server.injectUiAppVars('sentinl', () => { ... })"}

**Comment by Yavis** [comment]
Just wanted to ask if there are updates, will sentinl support kibana 6.3.0 from September 30th?

**Comment by vainkop** [comment]
Any updates on 6.3.0 support? A blocker for us to be able to use it on GKE with Elastic GKE Logging (Google Click to Deploy containers) which is 6.3 :(

**Comment by lmangani** [comment]
ALL: Yes, we're working on that! Just remember donations, help offers and contributions do help open-source happen! ;)

**Comment by vainkop** [comment]
Got you! Any time estimates on the release? :)

**Comment by nixiaode** [comment]
I'm waiting for 6.3.1,Can I ask when?

**Comment by sergibondarenko** [comment]
@nixiaode soon, but I can't give you any certain date. We work on it now.

**Comment by Ihsan8** [comment]
Thanks Grashee

**Comment by sergibondarenko** [comment]
@BFLB @Ihsan8 @Grashee @nixiaode @vainkop @TastyMuffins guys we have v6.4 pre-release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.1-beta
Version 6.3 will be available soon.

**Comment by Grashee** [comment]
> Version 6.3 will be available soon.

If there is a version for 6.3 I will use it

Cheers!
Robert

**Comment by sergibondarenko** [comment]
@BFLB @Ihsan8 @Grashee @nixiaode @vainkop @TastyMuffins @havlan  guys, we have v6.3 pre-release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.3.2-beta-1

**Comment by OpakAlex** [comment]
Thanks!

**Comment by Yavis** [comment]
Thank you very much!
