### ISSUE TITLE
Error, when try to save watcher from wizard

### ISSUE THREAD

**Issue by metal-doctor** [sirensolutions/sentinl#523]
1. Sentinl and Kibana version 
tag-6.2.4-pre-0/sentinl-v6.2.4-1 and 6.2.4

2. Issue description
I get error, when try to save watcher from wizard:
ThresholdWatcherWizard: fail to save watcher, Error: mapping set to strict, dynamic introduction of [impersonate] within [sentinl-watcher] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [impersonate] within [sentinl-watcher] is not allowed.

3. Reproducing the issue step-by-step
Try to save watcher from wizard.

6. Additional details
I use docker image sebp/elk:624.

**Comment by bienensenf** [comment]
I get the same error message just with field "save_payload" instead of impersonate. It is independent from wether I use the wizard or not. Just downloaded 6.2.4-4 a few hours ago. Can confirm it is not the case with version 6.2.3-3

**Comment by sergibondarenko** [comment]
@metal-doctor @bienensenf 

Sentinl needs to modify `.kibana` index by adding fields to its document (watcher) mappings there. And you created the `.kibana` index mapping when you created the index, before Sentinl installation. By default, Elasticsearch doesn't allow you to change the mapping.

The message doesn't appear if you install Sentinl before the Kibana first start (before `.kibana` index was created) because Sentinl mapping is registered during the index creation phase.   

Now there are 3 options to solve your problem:

A. Allow dynamic mappings for `.kibana` index by executing this in Kibana dev tools:
```
PUT .kibana/_mappings/doc {
  "dynamic": "true"
}
```
B. If you don't care about your old data, just delete `.kibana` index. Then restart Kibana.
```
DELETE .kibana
```
C. If you care about your data. 
  1. Install [elasticdump](https://www.npmjs.com/package/elasticdump) on Kibana server: `npm install elasticdump`
  2. Backup index data:
    ```
    elasticdump \
      --input=http://host:9200/.kibana \
      --output=http://host:9200/kibana_backup \
      --type=data
    ```
  3. Delete index: `curl -X DELETE "localhost:9200/.kibana"`
  4. Install Sentinl (if it is not installed)
  5. Start Kibana. Make sure the new `.kiabna` was created.
  6. Restore data:
    ```
    elasticdump \
      --input=http://host:9200/kibana_backup \
      --output=http://host:9200/.kibana \
      --type=data
    ```

**Comment by bienensenf** [comment]
Thank you @sergibondarenko that was it.
