### ISSUE TITLE
[save_payload] within [sentinl-watcher] is not allowed?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#548]
1. Sentinl and Kibana version 6.2.4

2. [save_payload] within [sentinl-watcher] is not allowed

3. advanced > save

4. Error: Watcher save: mapping set to strict, dynamic introduction of [save_payload] within [sentinl-watcher] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [save_payload] within [sentinl-watcher] is not allowed

**Comment by sergibondarenko** [comment]
@aabababb 

This is because we have new options in watcher. 

Sentinl needs to modify `.kibana` index by adding fields to its document (watcher) mappings there. And you created the `.kibana` index mapping when you created the index, before Sentinl installation. By default, Elasticsearch doesn't allow you to change the mapping.

The message doesn't appear if you install Sentinl before the Kibana first start (before `.kibana` index was created) because Sentinl mapping is registered during the index creation phase.   

Now there are 3 options to solve your problem:

A. Allow dynamic mappings for `.kibana` index by executing this in Kibana dev tools:
```
PUT .kibana/_mappings/doc {
  "dynamic": "true"
}
```
B. If you don't care about your old data, just delete `.kibana` index. Then restart Kibana.
```
DELETE .kibana
```
C. If you care about your data. 
  1. Install [elasticdump](https://www.npmjs.com/package/elasticdump) on Kibana server: `npm install elasticdump`
  2. Backup index data:
    ```
    elasticdump \
      --input=http://host:9200/.kibana \
      --output=http://host:9200/kibana_backup \
      --type=data
    ```
  3. Delete index: `curl -X DELETE "localhost:9200/.kibana"`
  4. Install Sentinl (if it is not installed)
  5. Start Kibana. Make sure the new `.kibana` index was created.
  6. Restore data:
    ```
    elasticdump \
      --input=http://host:9200/kibana_backup \
      --output=http://host:9200/.kibana \
      --type=data
    ```
