### ISSUE TITLE
how to get the query line?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#597]
**Kibana version:**6.2.4

**Elasticsearch version:**6.2.4

**Server OS version:**red hat 7

**Browser version:**firefox 56

**Browser OS version:**

**Original install method (e.g. release pkg link, gulp, from source, etc.):**
pkg
**Describe the bug:**
add the query line to the payload.hits,and then  the alarm can show the query line?

`"query": "Exception AND NOT  (exception test)"`

**Comment by havlan** [comment]
@aabababb Please use the template provided so we can get some insight in what you want to accomplish 100%. If I understand you correctly, using script conditions may be the way to approach this.
In script conditions you can add a field to the payload, I don't know if the query can be extracted, but it's worth a shot.
In script conditions:
```
payload.hits.total > 100; payload.str = JSON.stringify(payload);
```
Something like that.

**Comment by sergibondarenko** [comment]
@aabababb Thanks for taking time to report an issue.
Please fill all the following fields to make sure we have all the data we need to help you. 
Also, make sure you use the latest release we issued 3 days ago  https://github.com/sirensolutions/sentinl/releases

**Tips:**

1. If your watcher is not executed, try to query Elasticsearch manually first. Do you receive the results you want for your query?
For example, on Linux, you can query Elasticsearch using `curl`:

curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    "match_all": {}
  }
}
'
-->


### System Details
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |         |
| Elasticsearc |         |
| Server OS    |         |
| Browser      |         |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

### Bug Details
#### Bug Description

#### Steps to Reproduce
1.
1.
1.

#### Expected Behavior

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Screenshots (if relevant)

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)

#### Any additional information

**Comment by sergibondarenko** [comment]
Lucene query is not supported yet. We support only Elasticsearch DSL query in the watcher input. But we have will add the Lucene query too. Follow this issue for future updates https://github.com/sirensolutions/sentinl/issues/608
